version: "3"

services:

    monerod:
        image: btcpayserver/monero:0.15.0.1-amd64
        restart: unless-stopped
        container_name: xmr_monerod
        entrypoint: sleep 999999
#        entrypoint: monerod --fixed-difficulty 200 --rpc-bind-ip=0.0.0.0 --confirm-external-bind --rpc-bind-port=18081 --block-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/block?cryptoCode=xmr&hash=%s" --testnet --no-igd --hide-my-port --offline
        volumes:
            - "monero_data:/home/monero/.bitmonero"
        ports:
            - "18081:18081"
    monero_wallet:
        image: btcpayserver/monero:0.15.0.1-amd64
        restart: unless-stopped
        container_name: xmr_wallet_rpc
        entrypoint: monero-wallet-rpc --testnet --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon  --daemon-address=monerod:18081 --wallet-file=/wallet/wallet.keys --password-file=/wallet/password --tx-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s"
        ports:
            - "18082:18082"
        volumes:
            - "./monero_wallet:/wallet"
        depends_on:
            - monerod
        
volumes:
    monero_data:
