version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true
    steps: 
      - checkout
  test:
    docker:
      - image: microsoft/dotnet:2.1.403-sdk-alpine3.7
    steps:
      - checkout
      - run:
          command: |
            dotnet --info
            dotnet build /p:TreatWarningsAsErrors=true
            cd BTCPayServer.Tests
            dotnet test --filter Fast=Fast
            docker-compose up -d dev
            dotnet test --filter Integration=Integration
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
