blank_issues_enabled: false
contact_links: 
  - name: 🚀 Discussions  
    url: https://chat.btcpayserver.org/
    about: Technical discussions, questions and feature requests    
  - name: 📝 Official Documentation
    url: https://github.com/btcpayserver/btcpayserver/discussions
    about: Check our documentation for answers to common questions 
  - name: 💬 Community Support Chat  
    url: https://chat.btcpayserver.org/
    about: Ask general questions and get community support in real-time