version: "3"

services:
  nbxplorer:
    image: nicolasdorier/nbxplorer
    ports: 
      - 23001:23001
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_RPCURL: http://bitcoind:49372/
      NBXPLORER_RPCUSER: ceiwHEbqWI83
      NBXPLORER_RPCPASSWORD: DwubwWsoo3
      NBXPLORER_NODEENDPOINT: bitcoind:8332
      NBXPLORER_NOAUTH: 1
    links:
      - bitcoind

  bitcoind:
    image: nicolasdorier/bitcoin:0.15.0.1
    environment:
      BITCOIN_EXTRA_ARGS: "regtest=1\nrpcport=49372\nport=8332"
      BITCOIN_RPC_USER: ceiwHEbqWI83
      BITCOIN_RPC_PASSWORD: DwubwWsoo3
    expose:
      - "49372"
      - "8332"
    ports:
      - 49372:49372

  btcpayserver:
    ports: 
      - 23001:23001
    build:
      context: .
      dockerfile: DockerFile
  
  postgres:
    image:  postgres:9.6.5
